# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AnafiDetection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'GroundSdk', '~> 1.2.1'
  pod 'ArsdkEngine', '~> 1.2.1'
  pod 'SdkCore', '~> 1.2.1'
  pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']

end
